### ISSUE TITLE
Getting error while "downloading dependencies"

### ISSUE THREAD

**Issue by nick-77** [inotia00/rvx-builder#102]
**Describe the bug**
TypeError: Cannot read properties of undefined (reading 'split')
    at updateFiles (/data/data/com.termux/files/home/rvx-builder/wsEvents/updateFiles.js:30:26)
    at WebSocket.<anonymous> (/data/data/com.termux/files/home/rvx-builder/index.js:175:15)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/data/data/com.termux/files/home/rvx-builder/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/data/data/com.termux/files/home/rvx-builder/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/data/data/com.termux/files/home/rvx-builder/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/data/data/com.termux/files/home/rvx-builder/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/data/data/com.termux/files/home/rvx-builder/node_modules/ws/lib/receiver.js:83:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)
 
**To Reproduce**

Ran "./rvx-builder.sh" from termux, opened the browser and getting error while downloading dependencies 

**Screenshots**
![1000020309.jpg](https://github.com/inotia00/rvx-builder/assets/27954458/1f6f144d-3d5c-4ee8-b969-39aca3decfd1)

**revanced-builder Version:** 
3.9.6

**Desktop (please complete the following information):**

- OS: [e.g. Windows]
- Version: [e.g. 10]

**Additional context**
I just updated rvx builder to latest version

**Comment by inotia00** [comment]
reinstall
