### ISSUE TITLE
Patcher fails to initialize

### ISSUE THREAD

**Issue by bnm12** [inotia00/rvx-builder#106]
**Describe the bug**
Patcher fails to start

**To Reproduce**

1. Start app
2. Click on Start patching
3. See error

**revanced-builder Version:** v3.9.6

**Desktop (please complete the following information):**

- OS: Windows
- Version: 11

**Additional context**
Log output:

```[builder] An error occured.
TypeError: Cannot read properties of undefined (reading 'split')
    at updateFiles (C:\snapshot\rvx-builder2\wsEvents\updateFiles.js:30:26)
    at WebSocket.<anonymous> (C:\snapshot\rvx-builder2\index.js:175:15)
    at WebSocket.emit (node:events:537:28)
    at Receiver.receiverOnMessage (C:\snapshot\rvx-builder2\node_modules\ws\lib\websocket.js:1178:20)
    at Receiver.emit (node:events:537:28)
    at Receiver.dataMessage (C:\snapshot\rvx-builder2\node_modules\ws\lib\receiver.js:528:14)
    at Receiver.getData (C:\snapshot\rvx-builder2\node_modules\ws\lib\receiver.js:446:17)
    at Receiver.startLoop (C:\snapshot\rvx-builder2\node_modules\ws\lib\receiver.js:148:22)
    at Receiver._write (C:\snapshot\rvx-builder2\node_modules\ws\lib\receiver.js:83:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)
[builder] Please report this bug here: https://github.com/inotia00/rvx-builder/issues.

**Comment by inotia00** [comment]
https://github.com/inotia00/rvx-builder/issues/105
