### ISSUE TITLE
NoClassDefFoundError loading patches

### ISSUE THREAD

**Issue by Packsolite** [inotia00/rvx-builder#132]
Trying to patch youtube 17.34.36 for android 7 fails with this exception:
```
[builder] INFORMATION: Loading patches
[builder] Exception in thread "main"
[builder] java.lang.NoClassDefFoundError: app/revanced/patcher/fingerprint/method/impl/MethodFingerprint
[builder] at java.base/java.lang.ClassLoader.defineClass1(Native Method) at java.base/java.lang.ClassLoader.defineClass(Unknown Source) at java.base/java.security.SecureClassLoader.defineClass(Unknown Source) at java.base/java.net.URLClassLoader.defineClass(Unknown Source)
[builder] at java.base/java.net.URLClassLoader$1.run(Unknown Source) at java.base/java.net.URLClassLoader$1.run(Unknown Source) at java.base/java.security.AccessController.doPrivileged(Unknown Source) at java.base/java.net.URLClassLoader.findClass(Unknown Source) at java.base/java.lang.ClassLoader.loadClass(Unknown Source) at java.base/java.lang.ClassLoader.loadClass(Unknown Source) at app.revanced.patcher.PatchBundleLoader$1.invoke(PatchBundleLoader.kt:47) at app.revanced.patcher.PatchBundleLoader$1.invoke(PatchBundleLoader.kt:46)
[builder] at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210) at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170) at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194) at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214) at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169) at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194) at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
[builder] at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194) at kotlin.collections.CollectionsKt__MutableCollectionsKt.addAll(MutableCollections.kt:129) at app.revanced.patcher.PatchBundleLoader.(PatchBundleLoader.kt:55) at app.revanced.patcher.PatchBundleLoader.(PatchBundleLoader.kt) at app.revanced.patcher.PatchBundleLoader.(PatchBundleLoader.kt:34) at app.revanced.patcher.PatchBundleLoader$Jar.(PatchBundleLoader.kt:102)
[builder] at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:259) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12) Caused by: java.lang.ClassNotFoundException: app.revanced.patcher.fingerprint.method.impl.MethodFingerprint at java.base/java.net.URLClassLoader.findClass(Unknown Source)
[builder] at java.base/java.lang.ClassLoader.loadClass(Unknown Source) at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ... 35 more
```

**To Reproduce**
Follow the instructions for Method 4 on https://github.com/kitadai31/revanced-patches-android6-7/wiki/How-to-build

**Screenshots**
![image](https://github.com/inotia00/rvx-builder/assets/102829507/cd8da361-0ae3-4bc0-928b-b4a1e14cbdfa)

**rvx-builder Version:** 18.5.0

**Desktop:**
- OS: Windows
- Version:  11

**Comment by inotia00** [comment]
Unfortunately, this patch is not compatible with rvx-builder

To support rvx-builder, revanced-cli-v4.0+ must be supported
