### ISSUE TITLE
Bug: Anti-Split fails if file path contains spaces

### ISSUE THREAD

**Issue by 54m4d** [inotia00/rvx-builder#147]
**Describe the bug**
When placing the executable file in a folder and attempting to build, an error occurs during the merging process.

**To Reproduce**
Just put the executable file in a folder of your choice and try to build.

**Screenshots**
```
[builder] Listening at port 8000
[builder] The webserver is now running!
[builder] Opening the app in the default browser... Done, check if a browser window has opened
[builder] An error occured.
Error: Command failed: java -jar C:\Users\admin\Desktop\RVX Builder\revanced\APKEditor-V1.3.9.jar m -i C:\Users\admin\Desktop\RVX Builder\revanced\com.reddit.frontpage.apkm -o C:\Users\admin\Desktop\RVX Builder\revanced\com.reddit.frontpage.apk
00.000 I: [MERGE] Using: APKEditor version 1.3.9, ARSCLib version 1.3.5
00.018 I: [MERGE] Merging ...
   Input: C:\Users\admin\Desktop\RVX Builder\revanced\com.reddit.frontpage.apkm
 Output: C:\Users\admin\Desktop\RVX Builder\revanced\com.reddit.frontpage.apk
 ----------------------------
00.018 I: [MERGE] Extracting to: C:\Users\admin\Desktop\RVX Builder\revanced\tmp_1e717eaa

ERROR:
com.reandroid.archive.ArchiveException: Failed to find end record
        at com.reandroid.archive.block.EndRecord.findEndRecord(EndRecord.java:89)
        at com.reandroid.archive.block.EndRecord.findEndRecord(EndRecord.java:62)
        at com.reandroid.archive.model.CentralFileDirectory.visit(CentralFileDirectory.java:48)
        at com.reandroid.archive.Archive.<init>(Archive.java:46)
        at com.reandroid.archive.ArchiveFile.<init>(ArchiveFile.java:30)
        at com.reandroid.archive.ArchiveFile.<init>(ArchiveFile.java:33)
        at com.reandroid.apkeditor.merge.Merger.extractFile(Merger.java:106)
        at com.reandroid.apkeditor.merge.Merger.run(Merger.java:55)
        at com.reandroid.apkeditor.merge.Merger.execute(Merger.java:235)
        at com.reandroid.apkeditor.Main.execute(Main.java:89)
        at com.reandroid.apkeditor.Main.execute(Main.java:64)
        at com.reandroid.apkeditor.Main.main(Main.java:36)

    at ChildProcess.exithandler (node:child_process:389:12)
    at ChildProcess.emit (node:events:537:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
[builder] Please report this bug here: https://github.com/inotia00/rvx-builder/issues.
```
**rvx-builder Version:** v3.15.1

**Desktop (please complete the following information):**

Windows 10

**Additional context**
This issue does not occur when the executable file is run directly from the desktop.

**Comment by 54m4d** [comment]
I'm also getting this:
```
[builder] Listening at port 8000
[builder] The webserver is now running!
[builder] Opening the app in the default browser... Done, check if a browser window has opened
[builder] An error occured.
Error: Command failed: java -jar C:\Users\admin\Desktop\RVX Builder\revanced\APKEditor-V1.3.9.jar m -i C:\Users\admin\Desktop\RVX Builder\revanced\com.reddit.frontpage.apkm -o C:\Users\admin\Desktop\RVX Builder\revanced\com.reddit.frontpage.apk
Error: Unable to access jarfile C:\Users\admin\Desktop\RVX

    at ChildProcess.exithandler (node:child_process:389:12)
    at ChildProcess.emit (node:events:537:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
[builder] Please report this bug here: https://github.com/inotia00/rvx-builder/issues.
```

**Comment by 54m4d** [comment]
Some additional info:
Name of the exe file is: `Revnaced Builder.exe`

I'm also getting this error:
```
[builder] Listening at port 8000
[builder] The webserver is now running!
[builder] Opening the app in the default browser... Done, check if a browser window has opened
[builder] An error occured.
Error: Command failed: java -jar C:\Users\admin\Desktop\RVX Builder\revanced\APKEditor-V1.3.9.jar m -i C:\Users\admin\Desktop\RVX Builder\revanced\com.reddit.frontpage.apkm -o C:\Users\admin\Desktop\RVX Builder\revanced\com.reddit.frontpage.apk
Error: Unable to access jarfile C:\Users\admin\Desktop\RVX

    at ChildProcess.exithandler (node:child_process:389:12)
    at ChildProcess.emit (node:events:537:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
[builder] Please report this bug here: https://github.com/inotia00/rvx-builder/issues.
```

**Comment by inotia00** [comment]
I forgot to fix the issue..
I will reflect it in the next release.

**Comment by inotia00** [comment]
fixed in https://github.com/inotia00/rvx-builder/releases/tag/v3.18.2
