### ISSUE TITLE
It doesn't work again

### ISSUE THREAD

**Issue by me2BOY** [inotia00/rvx-builder#16]
Error: EBUSY: resource busy or locked, unlink '\\?\D:\ReVanced\revanced-cache\1.apk'
    at unlinkSync (node:fs:1780:3)
    at _unlinkSync (node:internal/fs/rimraf:214:14)
    at rimrafSync (node:internal/fs/rimraf:195:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at rmSync (node:fs:1274:10)
    at afterBuild (C:\snapshot\rvx-builder-build3\wsEvents\patchApp.js:38:3)
    at Socket.<anonymous> (C:\snapshot\rvx-builder-build3\wsEvents\patchApp.js:219:53)

I worked at Windows 11, so I deleted and reinstall them, but it doesn't work again.

**Comment by Spacellary** [comment]
You can try the steps at https://github.com/inotia00/rvx-builder/issues/7#issuecomment-1296274651 and see if that works, if it does or doesn't even after reboot, check your Windows Environment PATHS and make sure the new JDK is set to the right Path in there. Hopefully this helps.

**Comment by inotia00** [comment]
issue with zulu 17 (windows)

refer https://github.com/inotia00/rvx-builder/issues/7#issuecomment-1296274651
