### ISSUE TITLE
Error: EBUSY: resource busy or locked,

### ISSUE THREAD

**Issue by mrGRINCH** [inotia00/rvx-builder#17]
[builder] An error occured.
Error: EBUSY: resource busy or locked, unlink '\\?\C:\Users\[redacted]\AppData\Roaming\IDM\revanced-cache\1.apk'
    at unlinkSync (node:fs:1780:3)
    at _unlinkSync (node:internal/fs/rimraf:214:14)
    at rimrafSync (node:internal/fs/rimraf:195:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at rmSync (node:fs:1274:10)
    at afterBuild (C:\snapshot\rvx-builder-build3\wsEvents\patchApp.js:38:3)
    at Socket.<anonymous> (C:\snapshot\rvx-builder-build3\wsEvents\patchApp.js:219:53)
[builder] Please report this bug here: https://github.com/inotia00/rvx-builder/issues.

**revanced-builder Version:** rvx-builder v3.4.16

Windows 10.

**Comment by Spacellary** [comment]
You can try the steps at https://github.com/inotia00/rvx-builder/issues/7#issuecomment-1296274651 and see if that works, if it does or doesn't, report back if you can. If It doesn't work even after reboot, check your Windows Environment PATHS and make sure the new JDK is set to the right Path in there. Hopefully this helps.

_Check the pinned issue~_

**Comment by inotia00** [comment]
duplicate https://github.com/inotia00/rvx-builder/issues/7#issuecomment-1296274651
