### ISSUE TITLE
Building failed.

### ISSUE THREAD

**Issue by Noir16** [inotia00/rvx-builder#24]
**Describe the bug**
Building failed.

**To Reproduce**
After building, it fails at the point of referring to 1.apk

**Screenshots**

**revanced-builder Version:**
`3.5.0`

**Desktop (please complete the following information):**
- OS: `Windows 10 Home`
- Version: `19044.1266-ja_jp`

**Additional context**
[builder] An error occured:
Error: EBUSY: resource busy or locked, unlink '\\?\C:\Users\​[Username]\Desktop\revanced-cache\1.apk'
at unlinkSync (node:fs:1780:3)
at _unlinkSync (node:internal/fs/rimraf:214:14)
at rimrafSync (node:internal/fs/rimraf:195:7)
at node:internal/fs/rimraf:253:9
at Array.forEach ()
at _rmdirSync (node:internal/fs/rimraf:250:7)
at rimrafSync (node:internal/fs/rimraf:193:7)
at rmSync (node:fs:1274:10)
at afterBuild (C:\snapshot\rvx-builder2\wsEvents\patchApp.js:38:3)
at Socket. (C:\snapshot\rvx-builder2\wsEvents\patchApp.js:200:53)
Please report this bug here: https://github.com/inotia00/rvx-builder/issues.

**Comment by Impulse666** [comment]
Give this a try: https://github.com/inotia00/rvx-builder/issues/7#issuecomment-1296274651

**Comment by Noir16** [comment]
I Installed the last Java 17 (LTS) x86 32-bit version.
but, it does not move to the next step with the output of the next message in the patching step.
>[builder] java.util.zip.ZipException: zip END header not found at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469) at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477) at java.base/java.util.zip.ZipFile$Source.(ZipFile.java:1315) at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277) at java.base/java.util.zip.ZipFile$CleanableResource.(ZipFile.java:709) at java.base/java.util.zip.ZipFile.(ZipFile.java:243) at java.base/java.util.zip.ZipFile.(ZipFile.java:172) at java.base/java.util.jar.JarFile.(JarFile.java:347) at java.base/java.util.jar.JarFile.(JarFile.java:318) at java.base/java.util.jar.JarFile.(JarFile.java:284) at app.revanced.patcher.util.patch.PatchBundle$Jar.loadPatches(PatchBundle.kt:44) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:140) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.main.MainKt.main(Main.kt:7)

**Comment by Impulse666** [comment]
Go to the Command Prompt and type these commands:
echo %JAVA_HOME%
java -version

What do you get?

**Comment by Noir16** [comment]
The cause was that `Set JAVA_HOME variable` was not checked in the Zulu JDK installation custom page.
Now that the build was successful, close this thread.

Issue resolution summary:
- Zulu installation on x32, not x64 Zulu JDK.
- Install by checking `Set JAVA_HOME variable` on the installation custom page. (Or run the uninstaller and click the `Change` button to check `Set JAVA_HOME variable` for additional installation.)
