### ISSUE TITLE
Fails when writing patched app

### ISSUE THREAD

**Issue by jas0npc** [inotia00/rvx-builder#38]
[builder] Listening at port 8000
[builder] The webserver is now running!
[builder] Opening the app in the default browser... Done, check if a browser window has opened
[builder] An error occured.
Error: EBUSY: resource busy or locked, unlink '\\?\C:\Users\jason\Downloads\revanced-cache\1.apk'
    at unlinkSync (node:fs:1780:3)
    at _unlinkSync (node:internal/fs/rimraf:214:14)
    at rimrafSync (node:internal/fs/rimraf:195:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at rmSync (node:fs:1274:10)
    at afterBuild (C:\snapshot\rvx-builder2\wsEvents\patchApp.js:28:3)
    at Socket.<anonymous> (C:\snapshot\rvx-builder2\wsEvents\patchApp.js:186:53)
[builder] Please report this bug here: https://github.com/inotia00/rvx-builder/issues.

**Comment by inotia00** [comment]
duplicate issue https://github.com/inotia00/rvx-builder/issues/7
