### ISSUE TITLE
Bug 🐛

### ISSUE THREAD

**Issue by Parsa307** [inotia00/rvx-builder#46]
[builder] An error occured.
FetchError: invalid json response body at https://www.apkmirror.com/wp-json/apkm/v1/app_exists/ reason: Unexpected token < in JSON at position 0
    at /data/data/com.termux/files/home/rvx-builder/node_modules/node-fetch/lib/index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchPackages (/data/data/com.termux/files/home/rvx-builder/wsEvents/getApp.js:19:20)
    at async getPatches (/data/data/com.termux/files/home/rvx-builder/wsEvents/getApp.js:40:16)
    at async WebSocket.<anonymous> (/data/data/com.termux/files/home/rvx-builder/index.js:175:9)
[builder] Please report this bug here: https://github.com/inotia00/rvx-builder/issues.

**Comment by inotia00** [comment]
https://github.com/inotia00/rvx-builder/issues/45
