### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by tranngoc7782** [inotia00/rvx-builder#50]
Error: EBUSY: resource busy or locked, unlink '\\?\C:\Users\trann\Downloads\YTB-Build\revanced-cache\1.apk'
    at unlinkSync (node:fs:1780:3)
    at _unlinkSync (node:internal/fs/rimraf:214:14)
    at rimrafSync (node:internal/fs/rimraf:195:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at rmSync (node:fs:1274:10)
    at afterBuild (C:\snapshot\rvx-builder2\wsEvents\patchApp.js:28:3)
    at Socket.<anonymous> (C:\snapshot\rvx-builder2\wsEvents\patchApp.js:186:53)

**Comment by inotia00** [comment]
https://github.com/inotia00/rvx-builder/issues/7#issuecomment-1296274651
