### ISSUE TITLE
Error when patching YouTube Music

### ISSUE THREAD

**Issue by s3tnex** [inotia00/rvx-builder#54]
During the final patching of YTMusic, this error pops up
Screenshot: https://imgur.com/a/7w2LJLp
revanced-builder Version: 3.8.0
- OS: Windows
- Version: 10

Log:
Error: EBUSY: resource busy or locked, unlink '\\?\C:\Users\danil\Desktop\rvx-builder\revanced-cache\1.apk'
    at unlinkSync (node:fs:1780:3)
    at _unlinkSync (node:internal/fs/rimraf:214:14)
    at rimrafSync (node:internal/fs/rimraf:195:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at rmSync (node:fs:1274:10)
    at afterBuild (C:\snapshot\rvx-builder2\wsEvents\patchApp.js:28:3)
    at Socket.<anonymous> (C:\snapshot\rvx-builder2\wsEvents\patchApp.js:186:53)

**Comment by inotia00** [comment]
Open task manager and force close Zulu
Then, delete the `revanced-cache` folder from the directory where rvx-builder is located
