### ISSUE TITLE
[builder] Error when patching YouTube Music

### ISSUE THREAD

**Issue by aprimasheva** [inotia00/rvx-builder#70]
These occured when patching YouTube Music, while YouTube was fine and no issue at all. I have tried to redownload everything, like redownloading builder, resources, etc. and not solved. I have tried the original builder from **_reisxd_** and it's fine. Hope you can fix these.
RVX Builder: v3.8.0
Platform: Laptop with Windows 11 installed

[builder] An error occured.
Error: EBUSY: resource busy or locked, unlink '\\?\D:\Program Files\ReVanced Extended Builder\revanced-cache\1.apk'
    at unlinkSync (node:fs:1780:3)
    at _unlinkSync (node:internal/fs/rimraf:214:14)
    at rimrafSync (node:internal/fs/rimraf:195:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at rmSync (node:fs:1274:10)
    at afterBuild (C:\snapshot\rvx-builder2\wsEvents\patchApp.js:28:3)
    at Socket.<anonymous> (C:\snapshot\rvx-builder2\wsEvents\patchApp.js:186:53)
[builder] Please report this bug here: `https://github.com/inotia00/rvx-builder/issues.`

**Comment by aprimasheva** [comment]
Solved by looking at this [#7 comment](https://github.com/inotia00/rvx-builder/issues/7#issuecomment-1296274651)
