### ISSUE TITLE
Kaput

### ISSUE THREAD

**Issue by tr1ckert** [inotia00/rvx-builder#81]
~ $ ./rvx-builder.sh
[rvx-builder] Already gotten storage access.
[rvx-builder] Node.js and JDK already installed.
[rvx-builder] rvx-builder found.
[rvx-builder] All checks done.

[builder] Listening at port 8000
[builder] The webserver is now running!
[builder] Opening the app in the default browser... Done, check if a browser window has opened
[builder] An error occured.
FetchError: invalid json response body at https://www.apkmirror.com/wp-json/apkm/v1/app_exists/ reason: Unexpected token < in JSON at position 0
    at /data/data/com.termux/files/home/rvx-builder/node_modules/node-fetch/lib/index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchPackages (/data/data/com.termux/files/home/rvx-builder/wsEvents/getApp.js:19:20)
    at async getPatches (/data/data/com.termux/files/home/rvx-builder/wsEvents/getApp.js:40:16)
    at async WebSocket.<anonymous> (/data/data/com.termux/files/home/rvx-builder/index.js:175:9)
[builder] Please report this bug here: https://github.com/inotia00/rvx-builder/issues.
[builder] An error occured.
FetchError: invalid json response body at https://www.apkmirror.com/wp-json/apkm/v1/app_exists/ reason: Unexpected token < in JSON at position 0
    at /data/data/com.termux/files/home/rvx-builder/node_modules/node-fetch/lib/index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchPackages (/data/data/com.termux/files/home/rvx-builder/wsEvents/getApp.js:19:20)
    at async getPatches (/data/data/com.termux/files/home/rvx-builder/wsEvents/getApp.js:40:16)
    at async WebSocket.<anonymous> (/data/data/com.termux/files/home/rvx-builder/index.js:175:9)
[builder] Please report this bug here: https://github.com/inotia00/rvx-builder/issues.
[builder] An error occured.
FetchError: invalid json response body at https://www.apkmirror.com/wp-json/apkm/v1/app_exists/ reason: Unexpected token < in JSON at position 0
    at /data/data/com.termux/files/home/rvx-builder/node_modules/node-fetch/lib/index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchPackages (/data/data/com.termux/files/home/rvx-builder/wsEvents/getApp.js:19:20)
    at async getPatches (/data/data/com.termux/files/home/rvx-builder/wsEvents/getApp.js:40:16)
    at async WebSocket.<anonymous> (/data/data/com.termux/files/home/rvx-builder/index.js:175:9)
[builder] Please report this bug here: https://github.com/inotia00/rvx-builder/issues.
[builder] An error occured.
FetchError: invalid json response body at https://www.apkmirror.com/wp-json/apkm/v1/app_exists/ reason: Unexpected token < in JSON at position 0
    at /data/data/com.termux/files/home/rvx-builder/node_modules/node-fetch/lib/index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchPackages (/data/data/com.termux/files/home/rvx-builder/wsEvents/getApp.js:19:20)
    at async getPatches (/data/data/com.termux/files/home/rvx-builder/wsEvents/getApp.js:40:16)
    at async WebSocket.<anonymous> (/data/data/com.termux/files/home/rvx-builder/index.js:175:9)
[builder] Please report this bug here: https://github.com/inotia00/rvx-builder/issues.

**Comment by inotia00** [comment]
your internet issue
turn off VPN

**Comment by tr1ckert** [comment]
Stupid me didn't think about that.
Thanks for still answering me, was indeed VPN.
